Update pipeline4

diff --git a/pipeline4 b/pipeline4
--- a/pipeline4
+++ b/pipeline4
@@ -1,1 +1,54 @@
+node("docker-slave-ssh") {
+        def mvnHome = tool name: 'M3'
+        List Env = [
+        "MVN=${mvnHome}/bin",
+        "M2_HOME=${mvnHome}"
+        ]
 
+        withEnv(Env) {
+        stage("Clone") {
+           sh 'cd /home/jenkins/ && git clone https://github.com/jenkinsci/prometheus-plugin && cd /home/jenkins/prometheus-plugin/ && git checkout prometheus-2.0.10'
+       }
+       try {
+          stage("Build") {
+              sh 'sleep $(shuf -i 30-60 -n 1) && cd /home/jenkins/prometheus-plugin/ && mvn clean install && mvn hpi:hpi'
+              sh '''
+                 #!/usr/bin/env bash
+                 ERR1=$(shuf -i0-3 -n1)             
+                 if [ ${ERR1} -eq "0" ]; then
+                    echo "Test stage success"
+                 else
+                    echo "Test stage failed"
+                    exit 1
+                 fi
+                 '''
+              currentBuild.result="SUCCESS"
+           }   
+         } catch(er) {
+                currentBuild.result="FAILURE"
+           }    
+       try {
+          stage("Test") {
+              sh 'sleep $(shuf -i 30-60 -n 1) && mvn test'
+              sh '''
+                 #!/usr/bin/env bash
+                 ERR2=$(shuf -i0-3 -n1)
+                 if [ ${ERR2} -eq "0" ]; then
+                    echo "Test stage success"
+                 else
+                    echo "Test stage failed"
+                    exit 1
+                 fi
+                 '''
+              currentBuild.result="SUCCESS"
+           }   
+         } catch(er) {
+                currentBuild.result="FAILURE"
+           }      
+       finally {
+             echo "${currentBuild.result}"
+             writeFile file: "artifact.txt", text: "${currentBuild.result}"
+             archiveArtifacts artifacts: "artifact.txt"
+       }
+}
+}
